---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volumes.etcd.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.etcd.size }}
